name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
    terraform:
      name: 'Terraform'
      runs-on: ubuntu-latest
      environment: production
  
      env:
        TF_VAR_bucket_name: ${{ secrets.bucket_name }}
        TF_VAR_project: ${{ secrets.project }}
        TF_VAR_region: ${{ secrets.region }}
        TF_VAR_organization: ${{ secrets.organization }}
        TF_VAR_workspace: ${{ secrets.workspace }}
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}
  
      defaults:
        run:
          shell: bash
  
      steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
  
        # Setup Terraform
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
        # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
        - name: Terraform Init
          run: terraform init
  
        # Checks that all Terraform configuration files adhere to a canonical format
        - name: Terraform Format
          run: terraform fmt -check
  
        # Generates an execution plan for Terraform
        - name: Terraform Plan
          run: terraform plan -input=false
  
        # Execute Terraform apply on push events to the "main" branch and pull requests
        - name: Terraform Apply
          if: github.ref == 'refs/heads/main'
          run: terraform apply -auto-approve -input=false
  