name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.2
  
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          PROJECT: ${{ secrets.PROJECT }}
          REGION: ${{ secrets.REGION }}
          ORGANIZATION: ${{ secrets.ORGANIZATION }}
          WORKSPACE: ${{ secrets.WORKSPACE }}
  
      - name: Terraform Plan
        run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          PROJECT: ${{ secrets.PROJECT }}
          REGION: ${{ secrets.REGION }}
          ORGANIZATION: ${{ secrets.ORGANIZATION }}
          WORKSPACE: ${{ secrets.WORKSPACE }}
  
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          PROJECT: ${{ secrets.PROJECT }}
          REGION: ${{ secrets.REGION }}
          ORGANIZATION: ${{ secrets.ORGANIZATION }}
          WORKSPACE: ${{ secrets.WORKSPACE }}
  